version: '3.8'
services:
  go-app:
    build: 
      context: .
      dockerfile: ./go-app.Dockerfile
    container_name: go-app
    image: go-app
    ports:
      - '8080:8080'
    networks:
      backend:

  nginx-app:
    build:
      context: .
      dockerfile: ./nginx.Dockerfile
    container_name: nginx-app
    image: nginx-app
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - 'go-app'
    networks:
      backend:

networks:
  backend:
    driver: bridge